Update classroom.yml

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -1,6 +1,6 @@
 name: GitHub Classroom Workflow
 
-on: 
+on:
   workflow_dispatch:
   push:
     paths-ignore:
@@ -13,34 +13,48 @@ permissions:
 
 jobs:
   Checking-Solution:
-    runs-on: gtest
+    runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
       - name: Get repository code
         uses: actions/checkout@v4
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install valgrind  # Install valgrind
+          # Add more dependencies if needed (e.g., gtest)
+
       - name: Build
         run: |
-             make
-             !(grep -qwRE --include=*.{cc,cpp,h} '<list>|<algorithm>|<stack>|<queue>|<deque>|<set>|<map>' ./* ) &&  (echo \"Build...\" )  || ( echo \"Forbiden STL containers\" && exit 9 )
+          make
+          if [ $? -ne 0 ]; then
+            echo "Build failed!"
+            exit 1
+          fi
+          !(grep -qwRE --include=*.{cc,cpp,h} '#include <(list|algorithm|stack|queue|deque|set|map)>' ./* ) &&  (echo \"Build...\" )  || ( echo \"Forbiden STL containers\" && exit 9 )
+
       - name: Autograding
         uses: amcp-pit/autograding@v1
+
       - name: Memory leaks
         run: |
-             valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./containers
+          valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./containers
+
       - name: Code linting
         uses: amcp-pit/cpp-linter@v1
         with:
           extra-args-before: '-xc++'
           after-args: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
-      - name: Checkout
-        uses: actions/checkout@v4
+
       - name: CPD
         uses: amcp-pit/cpd-action@v1
         id: cpd
         with:
           repository: ${{ github.repository }}
-          collection: ${{ github.repository_owner  }}
+          collection: ${{ github.repository_owner }}
+
       - name: Clean
         run: |
-             rm -rf ./* || true
-             rm -rf ./.??* || true
+          rm -rf ./* || true
+          rm -rf ./.??* || true
